name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2  # Change this to your region of your bucket
   
    - name: Sync to S3
      run: aws s3 cp . s3://icshin-web/s3-lab/ --recursive --include="*.css,*.html,*.js"  --exclude="*" # Change this to your bucket name